linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

run:
  timeout: 2m
  tests: true
issues:
  exclude-dirs:
    - examples
    - testdata
