package main

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/renderer/html"

	"github.com/manic/goweb/pkg/parser"
	"github.com/manic/goweb/pkg/preproc"
	"github.com/manic/goweb/pkg/weave"
)

// PageData is the template context passed to HTML templates.
type PageData struct {
	Title    string
	Content  template.HTML
	Source   string
	Chunks   []ChunkInfo
	Headings []Heading
}

// ChunkInfo holds metadata about a chunk for templates.
type ChunkInfo struct {
	Name     string
	Language string
	File     string
	Tags     []string
	Line     int
}

// Heading holds a single heading entry extracted from markdown content.
type Heading struct {
	Level int    // 1 for h1, 2 for h2, 3 for h3
	ID    string // anchor ID generated by goldmark
	Text  string // heading text
}

// SitePage holds data for a single page in site generation.
type SitePage struct {
	Title    string
	Content  template.HTML
	Path     string // relative path like "guide/install"
	Source   string // source .md path
	Chunks   []ChunkInfo
	Headings []Heading
	Children []SitePage
}

func registerRenderCmd() {
	renderCmd := &cobra.Command{
		Use:   "render <source.md> [source2.md ...]",
		Short: "Render literate programs to HTML using templates",
		Long: `Render weaves a goweb markdown file and renders it to HTML
using Go templates (similar to Jinja2).

Single file mode:
  goweb render program.md --template page.tmpl > output.html

Site mode (process a directory):
  goweb render --site docs/ --template page.tmpl --output-dir site/

Template variables:
  {{.Title}}    — First # heading from the document
  {{.Content}}  — Rendered HTML content (markdown converted)
  {{.Source}}   — Source .md file path
  {{.Chunks}}   — List of chunks with .Name, .Language, .File, .Tags

Example template (page.tmpl):
  <html><body>
    <h1>{{.Title}}</h1>
    <div>{{.Content}}</div>
  </body></html>`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			vars := parseVars(varFlags)
			siteDir, _ := cmd.Flags().GetString("site")
			tmplPath, _ := cmd.Flags().GetString("template")

			if siteDir != "" {
				return renderSite(siteDir, tmplPath, vars)
			}

			// Single file mode — use first arg.
			outputPath, _ := cmd.Flags().GetString("output")
			return renderFile(args[0], tmplPath, outputPath, vars)
		},
	}

	renderCmd.Flags().StringP("template", "t", "", "Go template file for HTML rendering")
	renderCmd.Flags().StringP("output", "o", "", "Output file (default: stdout)")
	renderCmd.Flags().StringP("site", "s", "", "Site mode: process a directory of .md files")
	renderCmd.Flags().StringVarP(&outputDir, "output-dir", "O", "", "Output directory for site mode")
	renderCmd.Flags().StringArrayVarP(&varFlags, "var", "v", nil,
		"Set a variable (key=value, can be specified multiple times)")
	rootCmd.AddCommand(renderCmd)
}

// renderFile processes a single .md file and renders it to HTML.
func renderFile(sourcePath, tmplPath, outputPath string, vars map[string]string) error {
	// Weave: strip goweb syntax.
	var buf bytes.Buffer
	if err := weave.Weave(sourcePath, vars, &buf, ""); err != nil {
		return fmt.Errorf("weaving: %w", err)
	}
	markdownContent := buf.String()

	// Convert markdown to HTML.
	mdRenderer := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)
	var htmlBuf bytes.Buffer
	if err := mdRenderer.Convert([]byte(markdownContent), &htmlBuf); err != nil {
		return fmt.Errorf("rendering markdown: %w", err)
	}

	// Build page data.
	title := extractTitle(markdownContent)
	chunks := extractChunkInfo(sourcePath, vars)
	headings := extractMarkdownHeadings(markdownContent)
	pageData := PageData{
		Title:    title,
		Content:  template.HTML(htmlBuf.String()),
		Source:   sourcePath,
		Chunks:   chunks,
		Headings: headings,
	}

	// Render through template or output raw HTML.
	var finalHTML string
	if tmplPath != "" {
		tmplContent, err := os.ReadFile(tmplPath)
		if err != nil {
			return fmt.Errorf("reading template: %w", err)
		}
		tmpl, err := template.New("page").Funcs(templateFuncs()).Parse(string(tmplContent))
		if err != nil {
			return fmt.Errorf("parsing template: %w", err)
		}
		var out bytes.Buffer
		if err := tmpl.Execute(&out, pageData); err != nil {
			return fmt.Errorf("executing template: %w", err)
		}
		finalHTML = out.String()
	} else {
		// Default template: Read the Docs inspired theme.
		finalHTML = renderDefaultTheme(pageData)
	}

	// Write output.
	if outputPath != "" {
		if err := os.WriteFile(outputPath, []byte(finalHTML), 0644); err != nil {
			return fmt.Errorf("writing output: %w", err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", outputPath)
	} else {
		fmt.Print(finalHTML)
	}
	return nil
}

// renderSite processes a directory of .md files into a static HTML site.
func renderSite(siteDir, tmplPath string, vars map[string]string) error {
	if outputDir == "" {
		return fmt.Errorf("--output-dir is required for site mode")
	}

	// Use custom template or default Read the Docs theme.
	useDefaultTheme := tmplPath == ""
	var tmpl *template.Template
	if !useDefaultTheme {
		tmplContent, err := os.ReadFile(tmplPath)
		if err != nil {
			return fmt.Errorf("reading template: %w", err)
		}
		tmpl, err = template.New("page").Funcs(template.FuncMap{
			"lower": strings.ToLower,
			"upper": strings.ToUpper,
		}).Parse(string(tmplContent))
		if err != nil {
			return fmt.Errorf("parsing template: %w", err)
		}
	}

	// Walk the directory for .md files.
	var pages []SitePage
	err := filepath.Walk(siteDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		page, err := buildPage(path, siteDir, vars)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error processing %s: %v\n", path, err)
			return nil
		}
		pages = append(pages, page)
		return nil
	})
	if err != nil {
		return fmt.Errorf("walking site directory: %w", err)
	}

	if len(pages) == 0 {
		return fmt.Errorf("no .md files found in %s", siteDir)
	}

	// Write pages.
	for _, page := range pages {
		var finalHTML string
		if useDefaultTheme {
			// Convert SitePage to PageData for default theme.
			finalHTML = renderDefaultTheme(PageData{
				Title:    page.Title,
				Content:  page.Content,
				Source:   page.Source,
				Chunks:   page.Chunks,
				Headings: page.Headings,
			})
		} else {
			var out bytes.Buffer
			if err := tmpl.Execute(&out, page); err != nil {
				fmt.Fprintf(os.Stderr, "error rendering %s: %v\n", page.Path, err)
				continue
			}
			finalHTML = out.String()
		}
		outPath := filepath.Join(outputDir, page.Path+".html")
		outDir := filepath.Dir(outPath)
		if err := os.MkdirAll(outDir, 0755); err != nil {
			return fmt.Errorf("creating directory: %w", err)
		}
		if err := os.WriteFile(outPath, []byte(finalHTML), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", outPath, err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
	}

	fmt.Fprintf(os.Stderr, "rendered %d pages\n", len(pages))
	return nil
}

// buildPage processes a single .md file into a SitePage.
func buildPage(path, siteDir string, vars map[string]string) (SitePage, error) {
	relPath, _ := filepath.Rel(siteDir, path)
	relPath = strings.TrimSuffix(relPath, ".md")

	var buf bytes.Buffer
	if err := weave.Weave(path, vars, &buf, ""); err != nil {
		return SitePage{}, fmt.Errorf("weaving: %w", err)
	}
	markdownContent := buf.String()

	// Convert markdown to HTML.
	mdRenderer := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)
	var htmlBuf bytes.Buffer
	if err := mdRenderer.Convert([]byte(markdownContent), &htmlBuf); err != nil {
		return SitePage{}, fmt.Errorf("rendering markdown: %w", err)
	}

	title := extractTitle(markdownContent)
	chunks := extractChunkInfo(path, vars)
	headings := extractMarkdownHeadings(markdownContent)

	return SitePage{
		Title:    title,
		Content:  template.HTML(htmlBuf.String()),
		Path:     relPath,
		Source:   path,
		Chunks:   chunks,
		Headings: headings,
	}, nil
}

// slugify converts a heading string to an HTML anchor ID,
// matching the default goldmark slugifier algorithm.
func slugify(s string) string {
	var out strings.Builder
	s = strings.ToLower(s)
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			out.WriteRune(r)
		} else if r == ' ' || r == '_' {
			if out.Len() > 0 && out.String()[out.Len()-1] != '-' {
				out.WriteRune('-')
			}
		}
	}
	result := out.String()
	result = strings.Trim(result, "-")
	return result
}

// extractMarkdownHeadings parses raw markdown content and returns
// all h1, h2, h3 headings with goldmark-compatible anchor IDs.
func extractMarkdownHeadings(markdown string) []Heading {
	var headings []Heading
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") {
			text := strings.TrimPrefix(trimmed, "# ")
			headings = append(headings, Heading{Level: 1, ID: slugify(text), Text: text})
		} else if strings.HasPrefix(trimmed, "## ") {
			text := strings.TrimPrefix(trimmed, "## ")
			headings = append(headings, Heading{Level: 2, ID: slugify(text), Text: text})
		} else if strings.HasPrefix(trimmed, "### ") {
			text := strings.TrimPrefix(trimmed, "### ")
			headings = append(headings, Heading{Level: 3, ID: slugify(text), Text: text})
		}
	}
	return headings
}

// extractTitle gets the first # heading from markdown content.
func extractTitle(markdown string) string {
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") {
			return strings.TrimPrefix(trimmed, "# ")
		}
	}
	return filepath.Base(markdown)
}

// extractChunkInfo parses the source and returns chunk metadata.
func extractChunkInfo(sourcePath string, vars map[string]string) []ChunkInfo {
	preprocResult, err := preproc.Process(sourcePath, vars)
	if err != nil {
		return nil
	}
	doc, err := parser.ParseLines(preprocResult.Lines, sourcePath)
	if err != nil {
		return nil
	}
	var info []ChunkInfo
	for _, c := range doc.Chunks {
		info = append(info, ChunkInfo{
			Name:     c.Name,
			Language: c.Language,
			File:     c.File,
			Tags:     c.Tags,
			Line:     c.Line,
		})
	}
	return info
}

// templateFuncs returns common template functions.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"lower": strings.ToLower,
		"upper": strings.ToUpper,
	}
}

// renderDefaultTheme generates a Sphinx/Read-the-Docs inspired HTML page
// with a dark sidebar, breadcrumb navigation, and responsive layout.
func renderDefaultTheme(data PageData) string {
	const defaultTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}} — goweb</title>
<style>
:root {
  --sidebar-bg: #2c3e50;
  --sidebar-text: #b3b3b3;
  --sidebar-active: #ffffff;
  --sidebar-link: #2980b9;
  --sidebar-width: 300px;
  --content-bg: #fcfcfc;
  --content-text: #404040;
  --content-link: #2980b9;
  --code-bg: #f5f5f5;
  --border: #e1e4e5;
  --mono-font: "SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --sidebar-bg: #1a1d23;
    --content-bg: #0d1117;
    --content-text: #c9d1d9;
    --content-link: #58a6ff;
    --code-bg: #161b22;
    --border: #30363d;
  }
}
* { box-sizing:border-box; margin:0; padding:0; }
html { scroll-behavior:smooth; }
body {
  font-family: system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  color: var(--content-text);
  background: var(--content-bg);
  display: flex;
  min-height: 100vh;
}
.sidebar {
  width: var(--sidebar-width);
  background: var(--sidebar-bg);
  color: var(--sidebar-text);
  position: fixed;
  top: 0; left: 0;
  height: 100vh;
  overflow-y: auto;
  z-index: 10;
  display: flex;
  flex-direction: column;
}
.sidebar-header { padding:24px 20px 16px; border-bottom:1px solid rgba(255,255,255,0.1); }
.sidebar-brand { color:#fff; font-size:1.25em; font-weight:700; text-decoration:none; }
.sidebar-search { margin-top:12px; }
.sidebar-search input {
  width:100%; padding:6px 12px;
  border:1px solid rgba(255,255,255,0.2); border-radius:4px;
  background:rgba(255,255,255,0.1); color:#fff; font-size:0.875em;
}
.sidebar-search input::placeholder { color:var(--sidebar-text); }
.sidebar-nav { flex:1; padding:8px 0; overflow-y:auto; }
.sidebar-nav ul { list-style:none; padding:0; }
.sidebar-nav li a {
  display:block; padding:5px 20px; color:var(--sidebar-text);
  text-decoration:none; font-size:0.9em;
  border-left:3px solid transparent;
}
.sidebar-nav li a:hover, .sidebar-nav li.current a {
  color:var(--sidebar-active); background:rgba(255,255,255,0.05);
}
.sidebar-nav li.current a { border-left-color:var(--sidebar-link); }
.sidebar-nav li.toctree-l2 a { padding-left:36px; }
.sidebar-nav li.toctree-l3 a { padding-left:52px; }
.sidebar-nav .sidebar-heading {
  padding:16px 20px 4px; font-size:0.75em;
  text-transform:uppercase; letter-spacing:0.1em;
  color:rgba(255,255,255,0.4); font-weight:600;
}
.sidebar-footer {
  padding:12px 20px; border-top:1px solid rgba(255,255,255,0.1);
  font-size:0.85em;
}
.sidebar-footer a { color:var(--sidebar-link); text-decoration:none; }
.sidebar-footer a:hover { text-decoration:underline; }
.content {
  margin-left: var(--sidebar-width);
  flex: 1;
  max-width: 100%;
  padding: 0;
}
.content-inner { max-width: 800px; padding: 40px 48px; margin: 0 auto; }
.breadcrumb {
  padding: 12px 48px; background: #fff;
  border-bottom: 1px solid var(--border);
  font-size: 0.85em; color: #999;
}
.breadcrumb a { color: var(--sidebar-link); text-decoration:none; }
.breadcrumb a:hover { text-decoration:underline; }
.breadcrumb span { color: var(--content-text); }
h1 { font-size:2em; margin:0 0 0.5em; color:#1a1a1a; font-weight:700; }
h2 { font-size:1.5em; margin:1.5em 0 0.5em; color:#1a1a1a; font-weight:700; }
h3 { font-size:1.25em; margin:1.25em 0 0.5em; color:#333; }
h4 { font-size:1em; margin:1.33em 0; font-weight:600; }
p { margin:1em 0; line-height:1.7; }
a { color:var(--content-link); text-decoration:none; }
a:hover { text-decoration:underline; }
code {
  font-family:var(--mono-font); background:var(--code-bg);
  padding:0.15em 0.4em; border-radius:3px; font-size:0.85em; color:#c7254e;
}
pre {
  background:var(--code-bg); border:1px solid var(--border);
  border-radius:3px; padding:12px 16px; overflow-x:auto;
  margin:1em 0; line-height:1.5;
}
pre code { background:none; padding:0; border-radius:0; color:inherit; }
blockquote {
  border-left:4px solid #2980b9; background:#eaf2f8;
  padding:12px 16px; margin:1em 0; border-radius:0 3px 3px 0;
}
blockquote p { margin:0; }
blockquote.warning { border-left-color:#e74c3c; background:#fdeaea; }
blockquote.note { border-left-color:#2980b9; background:#eaf2f8; }
blockquote.tip { border-left-color:#27ae60; background:#e8f8f0; }
table { border-collapse:collapse; width:100%; margin:1.5em 0; font-size:0.9em; }
th, td { border:1px solid var(--border); padding:8px 12px; text-align:left; }
th { background:#f5f5f5; font-weight:600; }
tr:nth-child(even) td { background:#fafafa; }
ul, ol { padding-left:2em; margin:1em 0; }
hr { border:none; border-top:1px solid var(--border); margin:2em 0; }
img { max-width:100%; height:auto; }
.chunk-table {
  margin:2em 0; border:1px solid var(--border);
  border-radius:3px; padding:12px 16px; background:#fafafa;
}
.chunk-table summary { cursor:pointer; font-weight:600; color:var(--content-link); font-size:0.9em; }
.chunk-table table { margin:0.5em 0 0; font-size:0.8em; }
.chunk-table th { background:#e8e8e8; }
.footer {
  margin-top:3em; padding-top:1.5em; border-top:2px solid var(--border);
  font-size:0.85em; color:#999; display:flex; justify-content:space-between;
}
.footer a { color:var(--sidebar-link); }
.sidebar-toggle {
  display:none; position:fixed; top:12px; left:12px; z-index:20;
  background:var(--sidebar-bg); color:#fff; border:none;
  border-radius:4px; padding:8px 12px; font-size:1.2em; cursor:pointer;
}
@media (max-width: 768px) {
  .sidebar { transform:translateX(-100%); transition:transform 0.3s ease; }
  .sidebar.open { transform:translateX(0); }
  .content { margin-left:0; }
  .content-inner, .breadcrumb { padding-left:24px; padding-right:24px; }
  .sidebar-toggle { display:block; }
}
@media (prefers-color-scheme: dark) {
  h1, h2, h3 { color:#e6edf3; }
  .breadcrumb { background:var(--content-bg); border-bottom-color:var(--border); }
  blockquote { background:#0d1d3a; }
  blockquote.warning { background:#2d1b1b; }
  blockquote.tip { background:#1b2d1b; }
  th { background:#21262d; }
  tr:nth-child(even) td { background:#161b22; }
  .chunk-table { background:#161b22; }
  .chunk-table th { background:#21262d; }
  code { color:#f0c674; }
  .footer { border-top-color:var(--border); }
}
</style>
</head>
<body>

<button class="sidebar-toggle" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button>

<nav class="sidebar" id="sidebar">
  <div class="sidebar-header">
    <a href="#" class="sidebar-brand">goweb</a>
    <div class="sidebar-search">
      <input type="text" placeholder="Search docs..." disabled>
    </div>
  </div>
  <div class="sidebar-nav">
    <ul>
      <li class="current"><a href="#">{{.Title}}</a></li>
    </ul>
    {{if .Headings}}
    <div class="sidebar-heading">On this page</div>
    <ul>
      {{range .Headings}}
      <li class="toctree-l{{.Level}}"><a href="#{{.ID}}">{{.Text}}</a></li>
      {{end}}
    </ul>
    {{end}}
  </div>
  <div class="sidebar-footer">
    <a href="{{.Source}}">View source</a>
  </div>
</nav>

<div class="content">
  <nav class="breadcrumb">
    <a href="#">Home</a> / <span>{{.Title}}</span>
  </nav>
  <div class="content-inner">
    <article>
      {{.Content}}
    </article>

    {{if .Chunks}}
    <details class="chunk-table">
      <summary>Code chunks ({{len .Chunks}})</summary>
      <table>
        <tr><th>Name</th><th>File</th><th>Tags</th><th>Line</th></tr>
        {{range .Chunks}}
        <tr><td><code>&lt;&lt;{{.Name}}&gt;&gt;</code></td><td>{{.File}}</td><td>{{join .Tags ", "}}</td><td>{{.Line}}</td></tr>
        {{end}}
      </table>
    </details>
    {{end}}

    <footer class="footer">
      <span>&copy; 2026 goweb</span>
      <span>Generated by <a href="https://github.com/manic/goweb">goweb</a></span>
    </footer>
  </div>
</div>

</body>
</html>`
	tmpl := template.Must(template.New("page").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(defaultTmpl))
	var out bytes.Buffer
	tmpl.Execute(&out, data)
	return out.String()
}
