package main

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	gparser "github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"

	goparser "github.com/manic/goweb/pkg/parser"
	"github.com/manic/goweb/pkg/preproc"
	"github.com/manic/goweb/pkg/weave"
)

// PageData is the template context passed to HTML templates.
type PageData struct {
	Title    string
	Content  template.HTML
	Source   string
	Chunks   []ChunkInfo
	Headings []Heading
}

// ChunkInfo holds metadata about a chunk for templates.
type ChunkInfo struct {
	Name     string
	Language string
	File     string
	Tags     []string
	Line     int
}

// Heading holds a single heading entry extracted from markdown content.
type Heading struct {
	Level int    // 1 for h1, 2 for h2, 3 for h3
	ID    string // anchor ID generated by goldmark
	Text  string // heading text
}

// SitePage holds data for a single page in site generation.
type SitePage struct {
	Title    string
	Content  template.HTML
	Path     string // relative path like "guide/install"
	Source   string // source .md path
	Chunks   []ChunkInfo
	Headings []Heading
	Children []SitePage
}

func registerRenderCmd() {
	renderCmd := &cobra.Command{
		Use:   "render <source.md> [source2.md ...]",
		Short: "Render literate programs to HTML using templates",
		Long: `Render weaves a goweb markdown file and renders it to HTML
using Go templates (similar to Jinja2).

Single file mode:
  goweb render program.md --template page.tmpl > output.html

Site mode (process a directory):
  goweb render --site docs/ --template page.tmpl --output-dir site/

Template variables:
  {{.Title}}    — First # heading from the document
  {{.Content}}  — Rendered HTML content (markdown converted)
  {{.Source}}   — Source .md file path
  {{.Chunks}}   — List of chunks with .Name, .Language, .File, .Tags

Example template (page.tmpl):
  <html><body>
    <h1>{{.Title}}</h1>
    <div>{{.Content}}</div>
  </body></html>`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			vars := parseVars(varFlags)
			siteDir, _ := cmd.Flags().GetString("site")
			tmplPath, _ := cmd.Flags().GetString("template")

			if siteDir != "" {
				return renderSite(siteDir, tmplPath, vars)
			}

			// Single file mode — use first arg.
			outputPath, _ := cmd.Flags().GetString("output")
			return renderFile(args[0], tmplPath, outputPath, vars)
		},
	}

	renderCmd.Flags().StringP("template", "t", "", "Go template file for HTML rendering")
	renderCmd.Flags().StringP("output", "o", "", "Output file (default: stdout)")
	renderCmd.Flags().StringP("site", "s", "", "Site mode: process a directory of .md files")
	renderCmd.Flags().StringVarP(&outputDir, "output-dir", "O", "", "Output directory for site mode")
	renderCmd.Flags().StringArrayVarP(&varFlags, "var", "v", nil,
		"Set a variable (key=value, can be specified multiple times)")
	rootCmd.AddCommand(renderCmd)
}

// renderFile processes a single .md file and renders it to HTML.
func renderFile(sourcePath, tmplPath, outputPath string, vars map[string]string) error {
	// Weave: strip goweb syntax.
	var buf bytes.Buffer
	if err := weave.Weave(sourcePath, vars, &buf, ""); err != nil {
		return fmt.Errorf("weaving: %w", err)
	}
	markdownContent := buf.String()

	// Expand {{var}} placeholders using --var flags.
	markdownContent = expandVars(markdownContent, vars)

	// Convert markdown to HTML with auto heading IDs.
	mdRenderer := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithParserOptions(gparser.WithAutoHeadingID()),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)
	var htmlBuf bytes.Buffer
	if err := mdRenderer.Convert([]byte(markdownContent), &htmlBuf); err != nil {
		return fmt.Errorf("rendering markdown: %w", err)
	}

	// Build page data.
	htmlContent := htmlBuf.String()
	title := extractTitle(markdownContent)
	chunks := extractChunkInfo(sourcePath, vars)
	headings := extractHeadingsFromHTML(htmlContent)
	pageData := PageData{
		Title:    title,
		Content:  template.HTML(htmlContent),
		Source:   sourcePath,
		Chunks:   chunks,
		Headings: headings,
	}

	// Render through template or output raw HTML.
	var finalHTML string
	if tmplPath != "" {
		tmplContent, err := os.ReadFile(tmplPath)
		if err != nil {
			return fmt.Errorf("reading template: %w", err)
		}
		tmpl, err := template.New("page").Funcs(templateFuncs()).Parse(string(tmplContent))
		if err != nil {
			return fmt.Errorf("parsing template: %w", err)
		}
		var out bytes.Buffer
		if err := tmpl.Execute(&out, pageData); err != nil {
			return fmt.Errorf("executing template: %w", err)
		}
		finalHTML = out.String()
	} else {
		// Default template: Read the Docs inspired theme.
		finalHTML = renderDefaultTheme(pageData)
	}

	// Write output.
	if outputPath != "" {
		if err := os.WriteFile(outputPath, []byte(finalHTML), 0644); err != nil {
			return fmt.Errorf("writing output: %w", err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", outputPath)
	} else {
		fmt.Print(finalHTML)
	}
	return nil
}

// renderSite processes a directory of .md files into a static HTML site.
func renderSite(siteDir, tmplPath string, vars map[string]string) error {
	if outputDir == "" {
		return fmt.Errorf("--output-dir is required for site mode")
	}

	// Use custom template or default Read the Docs theme.
	useDefaultTheme := tmplPath == ""
	var tmpl *template.Template
	if !useDefaultTheme {
		tmplContent, err := os.ReadFile(tmplPath)
		if err != nil {
			return fmt.Errorf("reading template: %w", err)
		}
		tmpl, err = template.New("page").Funcs(template.FuncMap{
			"lower": strings.ToLower,
			"upper": strings.ToUpper,
		}).Parse(string(tmplContent))
		if err != nil {
			return fmt.Errorf("parsing template: %w", err)
		}
	}

	// Walk the directory for .md files.
	var pages []SitePage
	err := filepath.Walk(siteDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		page, err := buildPage(path, siteDir, vars)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error processing %s: %v\n", path, err)
			return nil
		}
		pages = append(pages, page)
		return nil
	})
	if err != nil {
		return fmt.Errorf("walking site directory: %w", err)
	}

	if len(pages) == 0 {
		return fmt.Errorf("no .md files found in %s", siteDir)
	}

	// Write pages.
	for _, page := range pages {
		var finalHTML string
		if useDefaultTheme {
			// Convert SitePage to PageData for default theme.
			finalHTML = renderDefaultTheme(PageData{
				Title:    page.Title,
				Content:  page.Content,
				Source:   page.Source,
				Chunks:   page.Chunks,
				Headings: page.Headings,
			})
		} else {
			var out bytes.Buffer
			if err := tmpl.Execute(&out, page); err != nil {
				fmt.Fprintf(os.Stderr, "error rendering %s: %v\n", page.Path, err)
				continue
			}
			finalHTML = out.String()
		}
		outPath := filepath.Join(outputDir, page.Path+".html")
		outDir := filepath.Dir(outPath)
		if err := os.MkdirAll(outDir, 0755); err != nil {
			return fmt.Errorf("creating directory: %w", err)
		}
		if err := os.WriteFile(outPath, []byte(finalHTML), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", outPath, err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
	}

	fmt.Fprintf(os.Stderr, "rendered %d pages\n", len(pages))
	return nil
}

// buildPage processes a single .md file into a SitePage.
func buildPage(path, siteDir string, vars map[string]string) (SitePage, error) {
	relPath, _ := filepath.Rel(siteDir, path)
	relPath = strings.TrimSuffix(relPath, ".md")

	var buf bytes.Buffer
	if err := weave.Weave(path, vars, &buf, ""); err != nil {
		return SitePage{}, fmt.Errorf("weaving: %w", err)
	}
	markdownContent := buf.String()

	// Expand {{var}} placeholders.
	markdownContent = expandVars(markdownContent, vars)

	// Convert markdown to HTML with auto heading IDs.
	mdRenderer := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithParserOptions(gparser.WithAutoHeadingID()),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)
	var htmlBuf bytes.Buffer
	if err := mdRenderer.Convert([]byte(markdownContent), &htmlBuf); err != nil {
		return SitePage{}, fmt.Errorf("rendering markdown: %w", err)
	}

	htmlContent := htmlBuf.String()
	title := extractTitle(markdownContent)
	chunks := extractChunkInfo(path, vars)
	headings := extractHeadingsFromHTML(htmlContent)

	return SitePage{
		Title:    title,
		Content:  template.HTML(htmlContent),
		Path:     relPath,
		Source:   path,
		Chunks:   chunks,
		Headings: headings,
	}, nil
}

// extractHeadingsFromHTML parses rendered HTML content and extracts
// heading tags (h1-h3) with their goldmark-generated id attributes.
// This guarantees sidebar TOC links match the actual heading anchors.
func extractHeadingsFromHTML(htmlContent string) []Heading {
	var headings []Heading
	lines := strings.Split(htmlContent, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		for level := 1; level <= 3; level++ {
			prefix := fmt.Sprintf("<h%d id=\"", level)
			if strings.HasPrefix(trimmed, prefix) {
				rest := trimmed[len(prefix):]
				endQuote := strings.Index(rest, "\"")
				id := ""
				if endQuote >= 0 {
					id = rest[:endQuote]
					rest = rest[endQuote+1:]
				}
				// Extract text after the closing >.
				closeTag := strings.Index(rest, ">")
				var text string
				if closeTag >= 0 {
					inner := rest[closeTag+1:]
					endTag := strings.LastIndex(inner, "</h")
					if endTag >= 0 {
						text = inner[:endTag]
					} else {
						text = inner
					}
				}
				headings = append(headings, Heading{
					Level: level,
					ID:    id,
					Text:  stripHTMLTags(text),
				})
				break
			}
		}
	}
	return headings
}

// stripHTMLTags removes simple HTML tags from a string for clean heading display.
func stripHTMLTags(s string) string {
	var out strings.Builder
	inTag := false
	for _, r := range s {
		if r == '<' {
			inTag = true
			continue
		}
		if r == '>' {
			inTag = false
			continue
		}
		if !inTag {
			out.WriteRune(r)
		}
	}
	return strings.TrimSpace(out.String())
}

// expandVars replaces {{name}} placeholders with values from vars.
// Unknown variables are left as-is.
func expandVars(s string, vars map[string]string) string {
	if len(vars) == 0 {
		return s
	}
	var result strings.Builder
	i := 0
	for i < len(s) {
		start := strings.Index(s[i:], "{{")
		if start == -1 {
			result.WriteString(s[i:])
			break
		}
		start += i
		result.WriteString(s[i:start])

		end := strings.Index(s[start+2:], "}}")
		if end == -1 {
			result.WriteString(s[start:])
			break
		}
		end += start + 2

		varName := strings.TrimSpace(s[start+2 : end])
		if varName == "" {
			result.WriteString("{{}}")
			i = end + 2
			continue
		}

		if val, ok := vars[varName]; ok {
			result.WriteString(val)
		} else {
			// Variable not set — leave the placeholder as-is.
			result.WriteString(s[start : end+2])
		}
		i = end + 2
	}
	return result.String()
}

// extractTitle gets the first # heading from markdown content.
func extractTitle(markdown string) string {
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") {
			return strings.TrimPrefix(trimmed, "# ")
		}
	}
	return filepath.Base(markdown)
}

// extractChunkInfo parses the source and returns chunk metadata.
func extractChunkInfo(sourcePath string, vars map[string]string) []ChunkInfo {
	preprocResult, err := preproc.Process(sourcePath, vars)
	if err != nil {
		return nil
	}
	doc, err := goparser.ParseLines(preprocResult.Lines, sourcePath)
	if err != nil {
		return nil
	}
	var info []ChunkInfo
	for _, c := range doc.Chunks {
		info = append(info, ChunkInfo{
			Name:     c.Name,
			Language: c.Language,
			File:     c.File,
			Tags:     c.Tags,
			Line:     c.Line,
		})
	}
	return info
}

// templateFuncs returns common template functions.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"lower": strings.ToLower,
		"upper": strings.ToUpper,
	}
}

// renderDefaultTheme generates an HTML page that closely matches the
// Read the Docs (Sphinx RTD) theme, using the same CSS class names,
// HTML structure (wy-grid-for-nav, wy-nav-side, wy-nav-content-wrap, rst-content),
// typography (Lato + Roboto Slab), and highlight.js for code highlighting.
func renderDefaultTheme(data PageData) string {
	const defaultTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}} — goweb</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&family=Roboto+Slab:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/github.min.css" id="hljs-light">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/atom-one-dark.min.css" id="hljs-dark" disabled>
<style>
* { box-sizing:border-box; margin:0; padding:0; }
html { font-size:100%; }
.wy-body-for-nav { background:#fcfcfc; }
.wy-nav-side {
  position:fixed; top:0; bottom:0; left:0;
  width:300px; z-index:200;
  background:#2c3e50; overflow-x:hidden; overflow-y:hidden;
  min-height:100%; color:#f8f8f8;
}
.wy-side-scroll { width:320px; position:relative; overflow-x:hidden; overflow-y:auto; height:100%; }
.wy-side-nav-search {
  display:block; width:300px; padding:12px 18px;
  margin-bottom:0; z-index:200;
  background:#2980b9; text-align:center;
}
.wy-side-nav-search input[type=text] {
  width:100%; border-radius:50px; padding:6px 12px;
  border:none; font-size:0.875em;
  font-family:Lato,"Helvetica Neue",Helvetica,Arial,sans-serif;
}
.wy-side-nav-search .icon-home { color:#fcfcfc; font-size:1.25em; font-weight:700; text-decoration:none; }
.wy-menu-vertical { padding-bottom:2em; }
.wy-menu-vertical p.caption {
  color:#f8f8f8; font-size:0.85em; margin:12px 0 0;
  padding:0 18px; font-weight:700; text-transform:uppercase;
}
.wy-menu-vertical li { list-style:none; }
.wy-menu-vertical li a {
  display:block; position:relative; padding:4px 18px;
  color:#b3b3b3; line-height:1.4em;
  font-size:0.9em; text-decoration:none;
}
.wy-menu-vertical li a:hover {
  background:rgba(255,255,255,0.05); color:#fcfcfc;
}
.wy-menu-vertical li.current a {
  background:rgba(255,255,255,0.05); color:#fcfcfc;
  border-left:3px solid #2980b9;
}
.wy-menu-vertical li.toctree-l1 a { padding-left:18px; }
.wy-menu-vertical li.toctree-l2 a { padding-left:34px; }
.wy-menu-vertical li.toctree-l3 a { padding-left:50px; }
.wy-nav-content-wrap {
  margin-left:300px; background:#fcfcfc; min-height:100%;
}
.wy-nav-content {
  padding:24px 48px; max-width:800px; margin:0 auto;
}
.wy-nav-top {
  display:none; background:#2980b9; color:#fff;
  padding:10px 16px; line-height:50px;
  text-align:center; font-size:100%;
}
.wy-nav-top a { color:#fcfcfc; font-weight:700; }
.wy-breadcrumbs { padding:8px 0; margin-bottom:16px; }
.wy-breadcrumbs li {
  display:inline-block; list-style:none; font-size:0.85em;
  color:#999;
}
.wy-breadcrumbs li a { color:#2980b9; text-decoration:none; }
.wy-breadcrumbs li a:hover { text-decoration:underline; }
.wy-breadcrumbs li:before {
  content:"/"; padding:0 6px; color:#ccc;
}
.wy-breadcrumbs li:first-child:before { content:none; }
.wy-breadcrumbs li.wy-breadcrumbs-aside { float:right; }
.wy-breadcrumbs li.wy-breadcrumbs-aside a { color:#999; font-size:0.9em; }
.wy-breadcrumbs li.wy-breadcrumbs-aside a:hover { color:#2980b9; }

/* --- rst-content --- */
.rst-content { font-family:Lato,"Helvetica Neue",Helvetica,Arial,sans-serif; font-size:16px; line-height:1.6; color:#404040; }
.rst-content h1, .rst-content h2, .rst-content h3, .rst-content h4, .rst-content h5, .rst-content h6 {
  font-family:"Roboto Slab",ff-tisa-web-pro,Georgia,Arial,sans-serif;
  font-weight:700; color:#1a1a1a; margin-bottom:24px;
}
.rst-content h1 { font-size:2.25em; margin-top:0; }
.rst-content h2 { font-size:1.75em; margin-top:1.5em; }
.rst-content h3 { font-size:1.25em; margin-top:1.25em; color:#333; }
.rst-content h4 { font-size:1em; margin-top:1.33em; font-weight:700; }
.rst-content p { margin:0 0 24px; line-height:1.7; }
.rst-content a { color:#2980b9; text-decoration:none; }
.rst-content a:hover { text-decoration:underline; }
.rst-content code, .rst-content tt {
  font-family:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",Courier,monospace;
  color:#000; padding:2px 5px; font-size:0.85em;
  background:#f5f5f5;
}
.rst-content code.literal, .rst-content tt.literal { color:#e74c3c; white-space:normal; }
.rst-content a code, .rst-content a tt { color:#2980b9; }
.rst-content div[class^=highlight] {
  border:1px solid #e1e4e5; overflow-x:auto; margin:1px 0 24px;
}
.rst-content div[class^=highlight] pre {
  font-family:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",Courier,monospace;
  font-size:12px; line-height:1.4;
  white-space:pre; margin:0; padding:12px; display:block; overflow:auto;
  background:#fff;
}
.rst-content pre.literal-block {
  border:1px solid #e1e4e5; overflow-x:auto; margin:1px 0 24px;
  font-family:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",Courier,monospace;
  font-size:12px; line-height:1.4;
  white-space:pre; padding:12px; display:block; overflow:auto;
  background:#fff;
}
.rst-content blockquote {
  margin-left:24px; line-height:24px; margin-bottom:24px;
  border-left:4px solid #2980b9;
  background:#eaf2f8; padding:12px 16px;
}
.rst-content blockquote p { margin:0; }
.rst-content blockquote p + p { margin-top:0.75em; }
.rst-content blockquote.warning { border-left-color:#e74c3c; background:#fdeaea; }
.rst-content blockquote.note { border-left-color:#2980b9; background:#eaf2f8; }
.rst-content blockquote.tip { border-left-color:#27ae60; background:#e8f8f0; }
.rst-content table {
  border-collapse:collapse; width:100%; margin:0 0 24px; font-size:0.9em;
}
.rst-content th, .rst-content td {
  border:1px solid #e1e4e5; padding:8px 12px; text-align:left;
}
.rst-content th { background:#f5f5f5; font-weight:700; }
.rst-content tr:nth-child(even) td { background:#fafafa; }
.rst-content ul, .rst-content ol { padding-left:2em; margin:0 0 24px; }
.rst-content li { margin-bottom:0.5em; }
.rst-content hr { border:none; border-top:1px solid #e1e4e5; margin:2em 0; }
.rst-content img { max-width:100%; height:auto; }
.rst-content .section { margin-bottom:24px; }

/* --- Chunk table --- */
.chunk-table {
  margin:2em 0 24px; border:1px solid #e1e4e5;
  border-radius:3px; padding:12px 16px; background:#fafafa;
}
.chunk-table summary { cursor:pointer; font-weight:700; color:#2980b9; font-size:0.9em; }
.chunk-table table { margin:0.5em 0 0; font-size:0.8em; }
.chunk-table th { background:#e8e8e8; }

/* --- Footer --- */
.rst-footer-buttons { margin-top:24px; }
.btn {
  display:inline-block; font-weight:400; text-align:center;
  vertical-align:middle; cursor:pointer; border:none;
  padding:8px 16px; font-size:0.9em; border-radius:3px;
  text-decoration:none;
}
.btn-neutral {
  background:#f3f6f6; color:#404040; border:1px solid #e1e4e5;
}
.btn-neutral:hover { background:#e8ebed; text-decoration:none; }
.btn-neutral.float-right { float:right; }

/* --- Responsive --- */
@media (max-width: 768px) {
  .wy-nav-side { left:-300px; }
  .wy-nav-side.shift { left:0; }
  .wy-nav-content-wrap { margin-left:0; }
  .wy-nav-content-wrap.shift { position:relative; left:300px; }
  .wy-nav-top { display:block; }
}

/* --- Dark mode --- */
@media (prefers-color-scheme: dark) {
  .wy-body-for-nav { background:#0d1117; }
  .wy-nav-content-wrap { background:#0d1117; }
  .rst-content { color:#c9d1d9; }
  .rst-content h1, .rst-content h2, .rst-content h3, .rst-content h4 { color:#e6edf3; }
  .rst-content code, .rst-content tt { background:#161b22; color:#f0c674; }
  .rst-content div[class^=highlight] pre { background:#161b22; }
  .rst-content th { background:#21262d; }
  .rst-content tr:nth-child(even) td { background:#161b22; }
  .rst-content blockquote { background:#0d1d3a; }
  .rst-content blockquote.warning { background:#2d1b1b; }
  .rst-content blockquote.tip { background:#1b2d1b; }
  .chunk-table { background:#161b22; }
  .chunk-table th { background:#21262d; }
  .btn-neutral { background:#21262d; color:#c9d1d9; border-color:#30363d; }
}
</style>
</head>
<body class="wy-body-for-nav">

<div class="wy-grid-for-nav">

  <nav data-toggle="wy-nav-shift" class="wy-nav-side">
    <div class="wy-side-scroll">
      <div class="wy-side-nav-search">
        <a href="#" class="icon-home"> goweb</a>
        <form role="search" class="wy-form" action="#" method="get">
          <input type="text" name="q" placeholder="Search docs" disabled>
        </form>
      </div>
      <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
        <p class="caption" role="heading"><span class="caption-text">Page</span></p>
        <ul>
          <li class="current toctree-l1"><a href="#">{{.Title}}</a></li>
        </ul>
        {{if .Headings}}
        <p class="caption" role="heading"><span class="caption-text">On this page</span></p>
        <ul>
          {{range .Headings}}
          <li class="toctree-l{{.Level}}"><a href="#{{.ID}}">{{.Text}}</a></li>
          {{end}}
        </ul>
        {{end}}
        <p class="caption" role="heading"><span class="caption-text">Source</span></p>
        <ul>
          <li class="toctree-l1"><a href="{{.Source}}">View source</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">
    <nav class="wy-nav-top" aria-label="Mobile navigation menu">
      <i data-toggle="wy-nav-top" onclick="var s=document.querySelector('.wy-nav-side'),c=document.querySelector('.wy-nav-content-wrap');s.classList.toggle('shift');c.classList.toggle('shift')" style="cursor:pointer;position:absolute;left:12px;top:0;line-height:50px;font-size:1.5em;">☰</i>
      <a href="#">{{.Title}}</a>
    </nav>

    <div class="wy-nav-content">
      <div class="rst-content">

        <div role="navigation" aria-label="Page navigation">
          <ul class="wy-breadcrumbs">
            <li><a href="#" class="icon-home"> Home</a></li>
            <li class="breadcrumb-item active">{{.Title}}</li>
            <li class="wy-breadcrumbs-aside">
              <a href="{{.Source}}">View source</a>
            </li>
          </ul>
          <hr>
        </div>

        <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
          <div itemprop="articleBody">
            <div class="section">
              <article>
                {{.Content}}
              </article>
            </div>
          </div>
        </div>

        {{if .Chunks}}
        <details class="chunk-table">
          <summary>Code chunks ({{len .Chunks}})</summary>
          <table>
            <tr><th>Name</th><th>File</th><th>Tags</th><th>Line</th></tr>
            {{range .Chunks}}
            <tr><td><code>&lt;&lt;{{.Name}}&gt;&gt;</code></td><td>{{.File}}</td><td>{{join .Tags ", "}}</td><td>{{.Line}}</td></tr>
            {{end}}
          </table>
        </details>
        {{end}}

        <footer>
          <div class="rst-footer-buttons" role="navigation" aria-label="Footer">
            <a href="#" class="btn btn-neutral float-right">Next →</a>
          </div>
          <hr>
          <div role="contentinfo">
            <p>&copy; 2026 goweb. Generated by <a href="https://github.com/manic/goweb">goweb</a>.</p>
          </div>
        </footer>
      </div>
    </div>
  </section>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/highlight.min.js"></script>
<script>
(function() {
  var light = document.getElementById('hljs-light');
  var dark = document.getElementById('hljs-dark');
  function setTheme() {
    var d = window.matchMedia('(prefers-color-scheme: dark)').matches;
    light.disabled = d; dark.disabled = !d;
  }
  setTheme();
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', setTheme);
  document.querySelectorAll('.rst-content pre').forEach(function(pre) {
    if (pre.parentNode.className.indexOf('highlight') === -1) {
      var div = document.createElement('div');
      div.className = 'highlight';
      pre.parentNode.insertBefore(div, pre);
      div.appendChild(pre);
    }
  });
  hljs.highlightAll();
})();
</script>
</body>
</html>`
	tmpl := template.Must(template.New("page").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(defaultTmpl))
	var out bytes.Buffer
	tmpl.Execute(&out, data)
	return out.String()
}
