package main

import (
	"html/template"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExtractTitle(t *testing.T) {
	tests := []struct {
		name     string
		markdown string
		want     string
	}{
		{"simple h1", "# Hello", "Hello"},
		{"h1 with extra space", "#   Hello World", "Hello World"},
		{"no heading", "plain text\n\nsome content", "plain text\n\nsome content"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := extractTitle(tt.markdown)
			if got != tt.want && !strings.HasSuffix(got, tt.want) {
				t.Errorf("extractTitle(%q) = %q; want %q", tt.markdown, got, tt.want)
			}
		})
	}
}

func TestExtractHeadingsFromHTML(t *testing.T) {
	html := `<h1 id="main-title">Main Title</h1>
<p>Some text</p>
<h2 id="section-one">Section One</h2>
<p>More text</p>
<h3 id="sub-section">Sub Section</h3>
<p>Even more</p>
<h2 id="section-two">Section Two</h2>
`
	headings := extractHeadingsFromHTML(html)
	if len(headings) != 4 {
		t.Errorf("expected 4 headings, got %d", len(headings))
		return
	}
	if headings[0].Level != 1 || headings[0].Text != "Main Title" || headings[0].ID != "main-title" {
		t.Errorf("heading 0: got Level=%d Text=%q ID=%q", headings[0].Level, headings[0].Text, headings[0].ID)
	}
	if headings[1].Level != 2 || headings[1].Text != "Section One" || headings[1].ID != "section-one" {
		t.Errorf("heading 1: got Level=%d Text=%q ID=%q", headings[1].Level, headings[1].Text, headings[1].ID)
	}
	if headings[2].Level != 3 || headings[2].Text != "Sub Section" || headings[2].ID != "sub-section" {
		t.Errorf("heading 2: got Level=%d Text=%q ID=%q", headings[2].Level, headings[2].Text, headings[2].ID)
	}
	if headings[3].Text != "Section Two" {
		t.Errorf("heading 3 text = %q; want 'Section Two'", headings[3].Text)
	}
}

func TestExpandVars(t *testing.T) {
	vars := map[string]string{
		"NAME": "World",
		"VER":  "1.0",
	}
	tests := []struct {
		input string
		want  string
	}{
		{"Hello {{NAME}}!", "Hello World!"},
		{"Version {{VER}}", "Version 1.0"},
		{"No vars here", "No vars here"},
		{"{{MISSING}}", "{{MISSING}}"},
		{"{{}}", "{{}}"},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := expandVars(tt.input, vars)
			if got != tt.want {
				t.Errorf("expandVars(%q) = %q; want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestTemplateFuncs(t *testing.T) {
	fm := templateFuncs()
	if fn, ok := fm["lower"]; ok {
		result := fn.(func(string) string)("HELLO")
		if result != "hello" {
			t.Errorf("lower('HELLO') = %q; want 'hello'", result)
		}
	} else {
		t.Error("templateFuncs missing 'lower'")
	}
	if fn, ok := fm["upper"]; ok {
		result := fn.(func(string) string)("hello")
		if result != "HELLO" {
			t.Errorf("upper('hello') = %q; want 'HELLO'", result)
		}
	} else {
		t.Error("templateFuncs missing 'upper'")
	}
}

func TestRenderDefaultTheme(t *testing.T) {
	data := PageData{
		Title:   "Test Page",
		Content: template.HTML("<p>Hello world</p>"),
		Source:  "test.md",
		Chunks: []ChunkInfo{
			{Name: "main", File: "main.tsx", Tags: []string{"component"}, Line: 10},
		},
		Headings: []Heading{
			{Level: 1, ID: "test-page", Text: "Test Page"},
			{Level: 2, ID: "section", Text: "Section"},
		},
	}

	html := renderDefaultTheme(data)

	// Verify key structural elements exist.
	checks := []string{
		`<!DOCTYPE html>`,
		`class="sidebar"`,
		`class="sidebar-header"`,
		`class="sidebar-brand">goweb`,
		`Search docs...`,
		`class="sidebar-nav"`,
		`class="toctree-l1"`,
		`class="toctree-l2"`,
		`class="sidebar-footer"`,
		`View source`,
		`class="breadcrumb"`,
		`class="content-inner"`,
		`<article>`,
		`<p>Hello world</p>`,
		`class="chunk-table"`,
		`&lt;&lt;main&gt;&gt;`,
		`component`,
		`main.tsx`,
		`class="footer"`,
		`Generated by`,
		`github.com/manic/goweb`,
	}
	for _, check := range checks {
		if !strings.Contains(html, check) {
			t.Errorf("renderDefaultTheme output missing expected string: %q", check)
		}
	}

	// Verify no empty template errors.
	if strings.Contains(html, "<no value>") || strings.Contains(html, "{{") {
		t.Error("renderDefaultTheme output contains unexecuted template placeholders")
	}
}

func TestRenderDefaultThemeEmpty(t *testing.T) {
	// Test with minimal data (no chunks, no headings).
	data := PageData{
		Title:   "Minimal",
		Content: template.HTML("<p>Content</p>"),
		Source:  "min.md",
	}
	html := renderDefaultTheme(data)
	if !strings.Contains(html, "Minimal") {
		t.Error("title should appear in output")
	}
	if !strings.Contains(html, "Content") {
		t.Error("content should appear in output")
	}
	if strings.Contains(html, "<details class=\"chunk-table\"") {
		t.Error("chunk table should not appear when there are no chunks")
	}
}

func TestRenderFileIntegration(t *testing.T) {
	// Create a temporary .md file.
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "test.md")
	content := `# Integration Test

This is a test document with a chunk.

<<greeting>>=
Hello, World!
>>
`
	if err := os.WriteFile(srcPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	outputPath := filepath.Join(dir, "output.html")
	if err := renderFile(srcPath, "", outputPath, nil); err != nil {
		t.Fatal(err)
	}

	// Read and verify output.
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}
	html := string(data)

	checks := []string{
		`<!DOCTYPE html>`,
		`Integration Test`,
		`Hello, World!`,
		`class="sidebar"`,
		`class="chunk-table"`,
		`&lt;&lt;greeting&gt;&gt;`,
		`class="footer"`,
	}
	for _, check := range checks {
		if !strings.Contains(html, check) {
			t.Errorf("rendered HTML missing expected string: %q", check)
		}
	}
}

func TestRenderFileCustomTemplate(t *testing.T) {
	dir := t.TempDir()

	// Source .md.
	srcPath := filepath.Join(dir, "test.md")
	srcContent := `# Custom Template Test
Content body.
`
	if err := os.WriteFile(srcPath, []byte(srcContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Custom template.
	tmplPath := filepath.Join(dir, "template.tmpl")
	tmplContent := `<html><body><h1>{{.Title | upper}}</h1><div>{{.Content}}</div></body></html>`
	if err := os.WriteFile(tmplPath, []byte(tmplContent), 0644); err != nil {
		t.Fatal(err)
	}

	outputPath := filepath.Join(dir, "output.html")
	if err := renderFile(srcPath, tmplPath, outputPath, nil); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}
	html := string(data)

	if !strings.Contains(html, "CUSTOM TEMPLATE TEST") {
		t.Errorf("custom template with |upper should produce uppercase title")
	}
	if !strings.Contains(html, "Content body") {
		t.Errorf("custom template should include content")
	}
}

func TestExtractChunkInfo(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "chunks.md")
	content := `# Chunks

<<main>>= file: main.go tags: core
package main
>>
`
	if err := os.WriteFile(srcPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	info := extractChunkInfo(srcPath, nil)
	if len(info) == 0 {
		t.Fatal("expected at least one chunk info")
	}
	if info[0].Name != "main" {
		t.Errorf("chunk name = %q; want 'main'", info[0].Name)
	}
	if info[0].File != "main.go" {
		t.Errorf("chunk file = %q; want 'main.go'", info[0].File)
	}
	if len(info[0].Tags) < 1 || info[0].Tags[0] != "core" {
		t.Errorf("chunk tags = %v; want ['core']", info[0].Tags)
	}
}

func TestRenderSiteDefaultTheme(t *testing.T) {
	// Create a temp directory with a couple .md pages.
	siteDir := t.TempDir()

	page1 := filepath.Join(siteDir, "index.md")
	os.WriteFile(page1, []byte("# Home\nWelcome to the site."), 0644)

	page2 := filepath.Join(siteDir, "guide.md")
	os.WriteFile(page2, []byte("# Guide\n## Installation\nRun the setup."), 0644)

	outputDir := filepath.Join(siteDir, "_site")
	os.MkdirAll(outputDir, 0755)

	// Test with default theme (no --template).
	// renderSite requires outputDir to be set on the package variable.
	origOutputDir := outputDir
	outputDir = origOutputDir

	// We can't easily test renderSite directly due to the package-level outputDir var,
	// but we can verify buildPage works with default theme via renderDefaultTheme.
	page, err := buildPage(page1, siteDir, nil)
	if err != nil {
		t.Fatal(err)
	}
	if page.Title != "Home" {
		t.Errorf("page title = %q; want 'Home'", page.Title)
	}
	if !strings.Contains(string(page.Content), "Welcome to the site.") {
		t.Errorf("page content missing expected text")
	}

	page2b, err := buildPage(page2, siteDir, nil)
	if err != nil {
		t.Fatal(err)
	}
	if page2b.Title != "Guide" {
		t.Errorf("page2 title = %q; want 'Guide'", page2b.Title)
	}
	if len(page2b.Headings) != 2 {
		t.Errorf("page2 headings = %d; want 2", len(page2b.Headings))
	}
	if page2b.Headings[1].Text != "Installation" {
		t.Errorf("page2 heading[1] text = %q; want 'Installation'", page2b.Headings[1].Text)
	}
}
