package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/spf13/cobra"
)

func registerReverseCmd() {
	reverseCmd := &cobra.Command{
		Use:   "reverse <file-or-dir> [file-or-dir ...]",
		Short: "Convert source files (or a folder) into a goweb .md file",
		Long: `Reverse wraps each text file in a <<name>>= file: path chunk.

A directory argument is walked. Skips .git, node_modules, vendor, and binaries.

Example:
  goweb reverse main.go lib.go > program.md
  goweb reverse --output program.md src/`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			outputFile, _ := cmd.Flags().GetString("output")
			return runReverse(args, outputFile)
		},
	}

	reverseCmd.Flags().StringP("output", "o", "", "Output file (default: stdout)")
	rootCmd.AddCommand(reverseCmd)
}

var reverseSkipDirs = map[string]bool{
	".git": true, "node_modules": true, "vendor": true, "target": true,
	"dist": true, "__pycache__": true, ".venv": true, ".idea": true,
	".vscode": true, "out": true,
}

func runReverse(args []string, outputFile string) error {
	files, err := collectReverseFiles(args, outputFile)
	if err != nil {
		return err
	}

	var out strings.Builder
	out.WriteString("# Literate Program\n\n")
	out.WriteString("Generated by goweb reverse.\n\n")

	used := map[string]int{}
	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}
		name := uniqueChunkName(path, used)
		slash := filepath.ToSlash(path)
		out.WriteString(fmt.Sprintf("<<%s>>= file: %s\n", name, slash))
		out.WriteString(string(data))
		if !strings.HasSuffix(string(data), "\n") {
			out.WriteString("\n")
		}
		out.WriteString(">>\n\n")
	}

	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(out.String()), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", outputFile, err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s (%d file(s))\n", outputFile, len(files))
	} else {
		fmt.Print(out.String())
	}
	return nil
}

func collectReverseFiles(args []string, outputFile string) ([]string, error) {
	var outAbs string
	if outputFile != "" {
		outAbs, _ = filepath.Abs(outputFile)
	}
	seen := map[string]bool{}
	var files []string
	for _, arg := range args {
		info, err := os.Stat(arg)
		if err != nil {
			return nil, err
		}
		if info.IsDir() {
			err := filepath.WalkDir(arg, func(path string, d fs.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if d.IsDir() {
					if reverseSkipDirs[d.Name()] {
						return filepath.SkipDir
					}
					return nil
				}
				if shouldSkipReverseFile(path, outAbs) {
					return nil
				}
				abs, _ := filepath.Abs(path)
				if seen[abs] {
					return nil
				}
				seen[abs] = true
				files = append(files, filepath.ToSlash(path))
				return nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}
		if shouldSkipReverseFile(arg, outAbs) {
			continue
		}
		abs, _ := filepath.Abs(arg)
		if seen[abs] {
			continue
		}
		seen[abs] = true
		files = append(files, filepath.ToSlash(arg))
	}
	sort.Strings(files)
	return files, nil
}

func shouldSkipReverseFile(path, outAbs string) bool {
	if outAbs != "" {
		if abs, err := filepath.Abs(path); err == nil && abs == outAbs {
			return true
		}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	if bytesContainNUL(data) || !utf8.Valid(data) {
		return true
	}
	return false
}

func bytesContainNUL(b []byte) bool {
	for _, c := range b {
		if c == 0 {
			return true
		}
	}
	return false
}

func uniqueChunkName(path string, used map[string]int) string {
	name := chunkNameFromPath(path)
	n := used[name]
	used[name] = n + 1
	if n == 0 {
		return name
	}
	return fmt.Sprintf("%s-%d", name, n+1)
}

func chunkNameFromPath(path string) string {
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	name = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			return r
		}
		return '_'
	}, name)
	if name == "" {
		name = "file"
	}
	return name
}
