package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func registerReverseCmd() {
	reverseCmd := &cobra.Command{
		Use:   "reverse <source.go> [source.py ...]",
		Short: "Convert source code files into a goweb .md file",
		Long: `Reverse reads one or more source code files and produces a
goweb markdown file with each file wrapped in a <<name>>= file: path chunk.

This is useful for bootstrapping: taking existing code and turning it
into a literate program.

Example:
  goweb reverse main.go lib.go > program.md
  goweb reverse --output program.md main.go`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			outputFile, _ := cmd.Flags().GetString("output")
			return runReverse(args, outputFile)
		},
	}

	reverseCmd.Flags().StringP("output", "o", "", "Output file (default: stdout)")
	rootCmd.AddCommand(reverseCmd)
}

func runReverse(files []string, outputFile string) error {
	var out strings.Builder

	out.WriteString("# Literate Program\n\n")
	out.WriteString("Generated by goweb reverse.\n\n")

	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}

		name := chunkNameFromPath(path)
		out.WriteString(fmt.Sprintf("<<%s>>= file: %s\n", name, path))
		out.WriteString(string(data))
		if !strings.HasSuffix(string(data), "\n") {
			out.WriteString("\n")
		}
		out.WriteString(">>\n\n")
	}

	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(out.String()), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", outputFile, err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", outputFile)
	} else {
		fmt.Print(out.String())
	}
	return nil
}

// chunkNameFromPath derives a chunk name from a file path.
func chunkNameFromPath(path string) string {
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	// Replace non-alphanumeric characters.
	name = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			return r
		}
		return '_'
	}, name)
	if name == "" {
		name = "file"
	}
	return name
}
